### ISSUE TITLE
Maybe not make the classes final so people use mocks more easy

### ISSUE THREAD

**Issue by robert-baboi-playtech** [osiegmar/FastCSV#35]
Hi, would you maybe consider making the api classes not final?

I want to use your library but I don't want to introduce Powermock to be able to write my tests or write wrapper classes just to circumvent the final

Thank you

**Comment by mithutokder** [comment]
Hi,
I have scenario to append data in an existing csv file. As the CsvWriter class is final I am  not able to change the behavior of the writer class.

**Comment by osiegmar** [comment]
The reason for declaring those classes as final is basically due to the idea described in item 17 of the book _Effective Java_ by Joshua Bloch – "Design and document for inheritance or else prohibit it". The classes in FastCSV are not designed/meant for inheritance.

I'm sorry but I do not plan to change that.

**Comment by robert-baboi-playtech** [comment]
Alright, no problem I found a workaround (https://www.baeldung.com/mockito-final#configure-mocktio)
Thank you for the reply
