### ISSUE TITLE
Add CSV table row position

### ISSUE THREAD

**Issue by Jokero** [osiegmar/FastCSV#5]
Currently `CsvRow` has `originalLineNumber` property which represents line number in file but not in table.

Example:
```
planet,text // line 1 in file and line 1 in table view
Earth,"opan // line 2 in file and line 2 in table view
adsad
sdfsdf
sdfsdfsd
sdfsdfsd
sdfsfdsf"
Mars,marscool // line 8 in file, but line 3 in table view
```

**Comment by osiegmar** [comment]
I added the `originalLineNumber` because this information cannot be retrieved otherwise (due to multiline values but especially skipped lines). The logical record number however can be counted from the outside (by your code) – hence I don't plan to add support for it in order to keep performance as high as possible.
