### ISSUE TITLE
Direct access to the fields as String[]

### ISSUE THREAD

**Issue by dagnelies** [osiegmar/FastCSV#51]
Hi,

I know you've put some extra efforts to provide the `CsvRow.getFields()` as unmodiable List, but it would also be nice if the `String[]` is directly available.

The reason in my case is that my application was built upon another CSV parsing before, and handled all the rows as `String[]` ...so, swapping the CSV parsing with your library actually requires me to swap the `List<String>` from `getFields()` back to `String[]` to avoid rewriting too much code. However, this feels both cumbersome and unnessary since they are already available within the `CsvRow` ...just not accessible. It would be nice to expose it directly.

Since many Libs deal with `String[]` rows, I think it could actually help as drop-in replacement for several of them.

Greetings aus Stuttgart

**Comment by osiegmar** [comment]
Let me first explain some of the ideas behind that decision.

CsvRow does not expose internal representation for a variety of reasons (Best practices, Law of Demeter or simply PMD ([MethodReturnsInternalArray](http://www.ing.iac.es/~docs/external/java/pmd/rules/sunsecure.html)) and Spotbugs ([EI_EXPOSE_REP](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#ei-may-expose-internal-representation-by-returning-reference-to-mutable-object-ei-expose-rep)) errors). In addition to that a CsvRow is meant to be immutable (also a best practice for record like objects nowadays) and might even become a Java record when [JEP 384](https://openjdk.java.net/jeps/384) is finalized.

To ensure all this, the contained data (currently a string array) has to be either copied (via the `clone()` method) or wrapped into an unmodifiable list. While a list contains some additional functionality (like contains, indexOf, stream, toString and some others), the string array copy does not seem to have any advantages on its own.
Apart from this, the NamedCsvRow returns a `Map<String, String>` for `getFields()` – it seemed to be more consistent to also return a 'real' object for `getFields()` within CsvRow.

> The reason in my case is that my application was built upon another CSV parsing before

Don't blame me for your mistakes! ;-D
Seriously: I didn't aim to be compatible with any other implementation. I just did what I thought to be reasonable.

> Since many Libs deal with String[] rows, I think it could actually help as drop-in replacement for several of them.

To be honest, I don't think that any CSV parsing library could ever be a real **drop-in replacement**. Not only because of different API but also because of parsing differences – see my [comparison with other libraries](https://github.com/osiegmar/JavaCsvComparison).


Having said all this, I'm not entirely against the idea of returning a cloned version of the backed variable. I'm just not convinced yet. For the sake of simplicity I'd prefer to have only one `getFields()` method – breaking the interface would require a new major release.

Lets keep this issue open for a while to see if there are other opinions / reactions. Currently, I have to give it a -1 :-).


Anyway, thanks for your comment!

**Comment by osiegmar** [comment]
Closing this for now. Maybe it's time to re-open when/if [Frozen Arrays](https://openjdk.java.net/jeps/8261007) becomes reality.
